### ISSUE TITLE
Activation quantization

### ISSUE THREAD

**Issue by kaizizzzzzz** [mobiusml/gemlite#1]
Hi, it's very excited to see this kernel!

I'm interested in the activation quantization. I saw this repo support int8 activation quantization. For the int8 activation quantization, is it a channel-wise quantization (the vector only has one scaling point), or group-wise quantization (each activation vector is quantized with smaller group)? Thanks!

**Comment by mobicham** [comment]
Thank you! Only channel-wise done outside the kernel, grouping is missing as mentioned in <a href="https://github.com/mobiusml/gemlite?tab=readme-ov-file#limitations">the limitations</a>.
These kernels are not supposed to be used directly for production, as we explain in the blogpost, it is a set of <a>examples</a> that people can use as a starting point to build their own kernels. Adding grouping on top of the int8 activation version should be possible

**Comment by kaizizzzzzz** [comment]
I see. So this kernel uses channel-wise for both the weights and activation

**Comment by mobicham** [comment]
The template implementation uses scalars actually, but you can do the channel-wise weight/activation scaling outside the matmul, either pre or post result matmul. For example: `matmul(x, W*scale) = matmul(x, W)*scale` if it's post matmul. Unfortunately, you can't do this trick for grouping when the group-size doesn't equal the weight shapes.

Doing grouping inside the kernel simply requires translating the matrix index `W_idx` into the right group index, for example it would be something like `W_idx // group_size` I think. But it would probably require copying the meta-data (scales)  in the shared memory first otherwise it could slowdown things especially for lower group-sizes
