### ISSUE TITLE
Default accumulate dtype should be fp32?

### ISSUE THREAD

**Issue by MARD1NO** [mobiusml/gemlite#6]
I have noticed that default acc dtype is same as output matrix dtype. 

In 3090/4090, tensorcore tflops will be doubled when acc_dtype is fp16 compared to fp32. 

We always use fp32 to accumulate in matmul, I think it is better for accuracy, and the comparison to other low-bit-gemm is more fair. 

PS: I also observed when change to acc_type=fp32, it will slow down in 4bit weightonly cases.

**Comment by mobicham** [comment]
Hey! It only slightly improves the speed on the 3090 / 4090. That's why it outperforms Marlin in compute-bound settings. <a href="bitblas"> https://github.com/microsoft/BitBLAS/ </a> also uses fp16 acc. 
On the A100/H100, there's no speed-up which is strange. 
Since the goal is to get the fastest performance, it should be fp16 by default. You can also pass the `acc_dtype` directly to the constructor (currently not in master).

In terms of accuracy, the only issue is with A16W8, for which I added a dumping factor which scales down the weights and post-scales the accumulator. Otherwise, there's no significant difference in terms of decoding quality as long as the activation/weights range is in check!

**Comment by MARD1NO** [comment]
> On the A100/H100, there's no speed-up which is strange.

In data center GPUs, it is same peak tflops whether use fp16 / fp32 acc
![image](https://github.com/user-attachments/assets/53c5efb2-4317-4aa5-9b41-88d62b4c40cd)

Thanks for your reply :D

**Comment by mobicham** [comment]
Oh thanks, didn't know about this, explains many things!
